version: '3'
services:
  app:
    image: go-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redisdb
    environment:
      - ADDR=0.0.0.0:8080
      - MONGO_URI=mongodb://db:27017

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  redisdb:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

